bcgov/GDX-Analytics-microservice

cmslitemetadata_to_redshift/cmslitemetadata_to_redshift.py, google-api/google_directions.py, google-api/google_mybusiness.py, google-api/google_search.py, lib/logs.py, s3_to_redshift/asset_data_to_redshift.py, s3_to_redshift/build_derived_assets.py, s3_to_redshift/s3_to_redshift.py, sfts/redshift_to_s3.py, sfts/s3_to_sfts.py
- Console log stream now redirects to log file
- Removed INFO level log suppression of common modules
=> Remove CustomStreamHandler and explicit log levels

cmslitemetadata_to_redshift/cmslitemetadata_to_redshift.py, google-api/google_directions.py, google-api/google_mybusiness.py, google-api/google_search.py, s3_to_redshift/build_derived_assets.py, s3_to_redshift/cmslite_user_data_to_redshift.py
This PR:
- Add elapsed time to any microservice reports that didn't display it
- Added the config file name to the report used by each microservice
- Removes empty lists from report output
- Updates variable "movefile" to "outfile"
- Aligns minor report formatting differences
=> Report output improvements

s3_to_redshift/asset_data_to_redshift.py, s3_to_redshift/cmslite_user_data_to_redshift.py, s3_to_redshift/s3_to_redshift.py
- Resolves spacing issues in reports
- Resolves list enumeration issue where count started at 0
- Resolves remaining empty lists in report outputs
=> GDXDSD-3535-Report-Enhancements

google-api/google_search.json
Waiting on start dates from Google Search Console
=> Add AG ticket sites

s3_to_redshift/config.d/ldb_sku.json
@BJenning related to your branch cleanup request on `GDXDSD-3874-LDB`.
No test required, it's just a config change to update S3 path to files. I've manually moved the files into the correct place in client and processed inside S3.
=> change s3 dir for ldb_sku to old jira number

sfts/config.d/pmrp_qdata_daily.json, sfts/config.d/pmrp_qdata_dates.json, sfts/config.d/pmrp_qdata_range.json, sfts/dml/pmrp_qdata_daily.sql, sfts/dml/pmrp_qdata_dates.sql, sfts/dml/pmrp_qdata_range.sql
…column, with config for historical data unload
=> GDXDSD-4296 pmrp qdata to provide service_creation_duration_per_visit

s3_to_redshift/asset_data_to_redshift.py, s3_to_redshift/config.d/gov_assets.json
user_agent_http_request_header
referrer
referrer_source 
request_string
=> Truncate columns to less than varhcar limit

sfts/redshift_to_s3.py
- Adds our standard report function to redshift_to_s3.py
- Confirmed working with all config files
=> Implement STDOUT report for redshift_to_s3.py

google-api/dml/cmslite.google_pdt.sql, google-api/google_search.json, google-api/google_search.py
- Created dml folder
- added config line for dml
- extracted sql from google_search.oy and placed into .sql file in dml/
- open .sql file in gogle_search.py
=> Moved sql out of google_search and into dml folder GDXDSD-4314

s3_to_redshift/config.d/chatbot_reports.json, s3_to_redshift/ddl/microservice.chatbot_reports.sql, s3_to_redshift/s3_to_redshift.py
Reverts bcgov/GDX-Analytics-microservice#90
=> Revert "add archive folder, encoding, strip quotes (and chatbot config) "

s3_to_redshift/s3_to_redshift.py
This PR escapes pipes in columns with dtype object.
=> gdxdsd-4882 escape pipe in all object cols

s3_to_redshift/s3_to_redshift.py
This PR mitigates log pollution caused by the is_processed() function.
=> gdxdsd-4458 prohibit excess logging by is_processed

sfts/dml/sdpr_historical.sql, sfts/dml/sdpr_last_full_day.sql
Reverts bcgov/GDX-Analytics-microservice#91
=> Revert "GDXDSD-4823 include zscore columns for SDPR daily and historical"

google-api/google_directions.py
This PR replaces calls to deprecated Google My Business APIs with calls to their new ones.
=> Gdxdsd 4733 google business api integration

google-api/google_mybusiness.py, google-api/google_search.py
Some active code was commented out, new call  to report added. Will need to fix before full pull  request.
=> GDXDSD-5197 Updated googlesearch.py to  remove adding  new line character in report()

google-api/google_mybusiness.py, google-api/google_search.py
Reverts bcgov/GDX-Analytics-microservice#118 IM PRETTY SURE THIS IS THE RIGHT ONE.
=> Revert "GDXDSD-5197 Updated googlesearch.py to  remove adding  new line character in report()"

google-api/google_mybusiness.py, google-api/google_search.py
Redoing  changes made in branch GDXDSD-5197-google-search-removing-extra-spacing as they  were not the source of the error  in the cron job.
=> removing extra newline character from report

s3_to_redshift/s3_to_redshift.py
Added a line to track the number of items successfully processed.
=> Gdxdsd 5189 st to redshihft fix log report numbers

google-api/google_mybusiness.py
I made a mistake and rolled back to the wrong version of google-api. This is to repair the changes I  undid with that mistake.
=> re-adding comments on logging

google-api/google_directions.py, google-api/google_mybusiness.py, google-api/google_search.py
Updated OAuth process to a loopback protocol as OOB process is being phased out (GDXDSD-5298.)
=> updated oAuth process

google-api/google_search.json
See  https://apps.itsm.gov.bc.ca/jira/browse/GDXDSD-5274 for full documentation.
=> added iiobc.ca back as the permission error is fixed

google-api/README.md, google-api/google_directions.py, google-api/google_mybusiness.py, google-api/google_search.py
=> Gdxdsd-5298 OAuth update google api documentation

google-api/README.md, google-api/google_directions.py, google-api/google_mybusiness.py, google-api/google_search.py
Formatting and wording in README  may need work.
=> Updating Client ID OAuth process

s3_to_redshift/s3_to_redshift.py
Added try catch to line that throws error when too many columns are present. 
This allows us to exit gracefully and print a report.
=> Gdxdsd 4212 catching mis matching column numbers

looker_dashboard_usage/looker_dashboard_usage.json, looker_dashboard_usage/looker_dashboard_usage.py
Updated the report definition to update the success/failure status, enumerated the results details and provided more complete path to the S3 locations
=> Gdxdsd 5398 reformat looker dashboard usage report

google-api/google_directions.py
Removed this variable as it is no longer being used in reporting
=> removed bad_file variable

redshift_to_s3/README.md, redshift_to_s3/config.d/example.json, redshift_to_s3/config.d/pmrp_all.json, redshift_to_s3/config.d/pmrp_date_range.json, redshift_to_s3/config.d/pmrp_max_date.json, redshift_to_s3/config.d/pmrp_qdata_daily.json, redshift_to_s3/config.d/pmrp_qdata_dates.json, redshift_to_s3/config.d/pmrp_qdata_range.json, redshift_to_s3/config.d/sdpr_historical.json, redshift_to_s3/config.d/sdpr_last_full_day.json, redshift_to_s3/redshift_to_s3.py, s3_to_sfts/README.md, s3_to_sfts/config.d/example.json, s3_to_sfts/config.d/pmrp_all.json, s3_to_sfts/config.d/pmrp_date_range.json, s3_to_sfts/config.d/pmrp_max_date.json, s3_to_sfts/config.d/pmrp_qdata_daily.json, s3_to_sfts/config.d/pmrp_qdata_dates.json, s3_to_sfts/config.d/pmrp_qdata_range.json, s3_to_sfts/s3_to_sfts.py
Changes redshift_to_s3.py to:
1. Unloads data into s3 processed/batch/client/client_folder/...
2. Copies the data from processed/batch/client/client_folder/... into s3 client/client_folder/... (optionally adds the file extension while doing this)
3. If 2 is successful copies the data from processed/batch/client/client_folder/... into processed/good/client/client_folder/...
4. If 2 is unsuccessful, copies the data from processed/batch/client/client_folder/... into processed/bad/client/client_folder/...
5. Updated the configs to use more descriptive parameter names
Changes s3_to_sfts to:
1. Added the ability to specify a separate source and archive prefix
2. Split the single path parameters in the configs to separate source and archive paths
3. Changed the the …
=> Gdxdsd 5355 add optional file extention to redshift to s3

s3_to_sfts/s3_to_sfts.py
Addresses an error that caused previously processes objects in an S3 subfolder not specified in the config to be recognized as a object to be uploaded to SFTS.
Testing these changes requires modifications to the existing config files that are not a part of the PR. You can find these modified config files attached to the Jira ticket.
Background for testing:
The following is a link to where in S3 that s3_to_sfts.py looks for for files to process: https://s3.console.aws.amazon.com/s3/buckets/sp-ca-bc-gov-131565110619-12-microservices?prefix=client/doug_test/GDXDSD-5650/pmrp_gdx/pmrp_date_range/&region=ca-central-1
It will look for these files in 
- https://s3.console.aws.amazon.com/s3/buckets/sp-ca-bc-gov-131565110619-12-microservices?prefix=processed/good/client/d …
=> Gdxdsd 5650 s3 to sfts error 2023 02 28

redshift_to_s3/config.d/sbc-sdpr_historical.json, redshift_to_s3/config.d/sbc-sdpr_last_full_day_incremental.json, redshift_to_s3/config.d/sdpr_last_full_day_incremental.json, redshift_to_s3/dml/sbc-sdpr_historical.sql, redshift_to_s3/dml/sbc-sdpr_last_full_day_incremental.sql
1. Adds inaccurate_time and no_wait_visit columns to [sbc-sdpr_historical.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-5548-SDPR-related-data-from-SBC-TheQ/redshift_to_s3/dml/sbc-sdpr_historical.sql) and [sbc-sdpr_last_full_day_incremental.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-5548-SDPR-related-data-from-SBC-TheQ/redshift_to_s3/dml/sbc-sdpr_last_full_day_incremental.sql)
2. Updated the version subfolders of [sbc-sdpr_historical.json](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-5548-SDPR-related-data-from-SBC-TheQ/redshift_to_s3/config.d/sbc-sdpr_historical.json) and [sbc-sdpr_last_full_day_incremental.json](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-5548-SDPR-related- …
=> Gdxdsd 5548 sdpr related data from sbc the q

google-api/config_servicebc.json, google-api/dml/servicebc.mybusiness.sql, google-api/google_mybusiness_servicebc_derived.py
created config_servicebc.json file and dml/servicebc.json.
updated script documentation, argument parsing for config file. Pulled sql query out of script.
=> 4454- google_mybusiness_servicebc... work to remove sql query from script

redshift_to_s3/redshift_to_s3.py
Reverts bcgov/GDX-Analytics-microservice#189
Missed bug where it's not finding previously transferred files, causing everything to be reprocessed.
=> Revert "Gdxdsd 5682 fix redshift to s3 mishandling unspecified subfolders"

redshift_to_s3/config.d/pmrp_qdata_range.json
Updates the max_date specified in [pmrp_qdata_range.json](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6268-sbc-theq-historical-refresh-20230922/redshift_to_s3/config.d/pmrp_qdata_range.json) in preparation for a historical refresh of TheQ data for SBC.
Please note that some of the config file were modified so that the tests can run. The modified configs will be added to the ticket.
Testing instructions:
1. Review the config file: [pmrp_qdata_range.json](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6268-sbc-theq-historical-refresh-20230922/redshift_to_s3/config.d/pmrp_qdata_range.json)
2. Log into the ec2 instance through the following commands
```
awsmfa prod <AWS OTP>
microservice_ssm
cd …
```
=> Updated max date for hist load

google-api/Pipfile.lock, looker_dashboard_usage/Pipfile.lock
1. Updates the urllib3 python package to version 1.26.18 in the google-api and looker_dashboard_usage microservices
Please note that some of the files on ec2 has been modified for testing. All of these will be added to the ticket in Jira in a zip file
Testing instructions:
We'll be testing to make sure that the microservices are still able to run after upgrading urllib3 to it's new version. A microservice that runs without any errors in it's report will show that this is the case. 
1. Log into the ec2 instance using the following commands:
```
awsmfa prod <AWS OTP>
microservice_ssm
```
2. Navigate to the looker_dashboard_usage microservice:
```
cd /home/microservice/branch/GDXDSD-6357_dependabot_urllib3_part2/looker_dashboard_usage
```
3. Run the following …
=> Gdxdsd 6357 dependabot urllib3 part2

redshift_to_s3/config.d/webdata_healthgateway_app_ratings_daily.json, redshift_to_s3/config.d/webdata_healthgateway_app_ratings_monthly.json, redshift_to_s3/config.d/webdata_healthgateway_downloaded_cards_daily.json, redshift_to_s3/config.d/webdata_healthgateway_downloaded_cards_monthly.json, redshift_to_s3/config.d/webdata_healthgateway_downloaded_reports_daily.json, redshift_to_s3/config.d/webdata_healthgateway_downloaded_reports_monthly.json, redshift_to_s3/config.d/webdata_healthgateway_geographic_breakdown_daily.json, redshift_to_s3/config.d/webdata_healthgateway_geographic_breakdown_monthly.json, redshift_to_s3/config.d/webdata_healthgateway_overall_page_views_daily.json, redshift_to_s3/config.d/webdata_healthgateway_overall_page_views_monthly.json, redshift_to_s3/config.d/webdata_healthgateway_traffic_channels_daily.json, redshift_to_s3/config.d/webdata_healthgateway_traffic_channels_monthly.json, redshift_to_s3/dml/webdata_healthgateway_app_ratings_daily.sql, redshift_to_s3/dml/webdata_healthgateway_app_ratings_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_cards_daily.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_cards_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_reports_daily.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_reports_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_geographic_breakdown_daily.sql, redshift_to_s3/dml/webdata_healthgateway_geographic_breakdown_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_overall_page_views_daily.sql, redshift_to_s3/dml/webdata_healthgateway_overall_page_views_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_traffic_channels_daily.sql, redshift_to_s3/dml/webdata_healthgateway_traffic_channels_monthly.sql, s3_to_local/config_sample.json
1. Edits the s3_to_local [config_sample.json](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6512_healthgateway_data_feeds/s3_to_local/config_sample.json) file to remove a specific client name and replace it with something more general
2. Adds files for 6 sets of files for daily and monthly versions of automated webdata feeds for healthgateway in a csv format
Please note that some of the config file were modified so that the tests can run. The modified configs will be added to the ticket in a zip file.
Testing instructions:
1. Reviewe [config_sample.json](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6512_healthgateway_data_feeds/s3_to_local/config_sample.json) to check and make sure everything is generic an no client is …
=> Gdxdsd 6512 healthgateway data feeds

redshift_to_s3/dml/webdata_tran_assetsinternet_monthly.sql, redshift_to_s3/dml/webdata_tran_assetstrannet_monthly.sql
Updates the [webdata_tran_assetsinternet_monthly.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6634_tran_case_sensitive_url_fix/redshift_to_s3/dml/webdata_tran_assetsinternet_monthly.sql) and [webdata_tran_assetstrannet_monthly.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6634_tran_case_sensitive_url_fix/redshift_to_s3/dml/webdata_tran_assetstrannet_monthly.sql) dml files to use case insensitive asset URLs when joining to the cmslite metadata. 
The changes to the SQL have already been reviewed internally. The tests below are to just check and make sure the changes did not cause any errors in the running of the microservices.
Please note that some of the config file were modified so that the tests can run. The modified configs will be added to …
=> Changed asset_url in join to case instensitive version

redshift_to_s3/dml/webdata_healthgateway_app_ratings_daily.sql, redshift_to_s3/dml/webdata_healthgateway_app_ratings_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_cards_daily.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_cards_monthly.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_reports_daily.sql, redshift_to_s3/dml/webdata_healthgateway_downloaded_reports_monthly.sql
Updates the following DMLs to use the newly updated stable name PDTs :
- [webdata_healthgateway_app_ratings_daily.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/main/redshift_to_s3/dml/webdata_healthgateway_app_ratings_daily.sql)
- [webdata_healthgateway_app_ratings_monthly.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/main/redshift_to_s3/dml/webdata_healthgateway_app_ratings_monthly.sql)
- [webdata_healthgateway_downloaded_cards_daily.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/main/redshift_to_s3/dml/webdata_healthgateway_downloaded_cards_daily.sql)
- [webdata_healthgateway_downloaded_cards_monthly.sql](https://github.com/bcgov/GDX-Analytics-microservice/blob/main/redshift_to_s3/dml/webdata_healthgateway_downloa …
=> Updated dmls to use the new stable name PDT

mysql_to_s3/ config.d/example.json, mysql_to_s3/.pylintrc, mysql_to_s3/Pipfile, mysql_to_s3/Pipfile.lock, mysql_to_s3/README.md, mysql_to_s3/config.d/example.json, mysql_to_s3/dml/example.sql, mysql_to_s3/mysql_to_s3.py
Creates a proof of concept microservice that will transfer data out of a MySQL database and store the resulting file in S3. 
The microservice uses a config file full of settings to specify a query to run in the MySQL database. The python script will then take the results of that query and store them in a file that is placed into S3. 
Testing instructions:
1. Log into the ec2 instance through the following commands
```
awsmfa prod <AWS OTP>
microservice_ssm
cd /home/microservice/branch/GDXDSD-5704_mysql_to_s3/mysql_to_s3
```
2. Run the following command and compare its output to what's expected.
```
pipenv run python mysql_to_s3.py -c config.d/example.json
```
```
***The microservice ran successfully***
Report: mysql_to_s3.py
Config: config.d/example.json
DML: …
```
=> Gdxdsd 5704 mysql to s3

redshift_to_s3/Pipfile, redshift_to_s3/Pipfile.lock
Updated Pipfile for python 3.8
New Pipfile.lock created on microservice_ssm
=> GDXDSD-6713 updated to Python 3.8 via updating Pipfile

google-api/Pipfile, google-api/Pipfile.lock
Updates the google-api microservice's virtual environment to use Python 3.8. As there was no reference to the Python version in this microservice's README, no changes were made.
Testing the changes in this microservice requires some files to be modified. These test files will be attached to the ticket in a zip file
1. Review the virtual environment files to make sure the Python version is set to 3.8
- [Pipfile](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6714_python_3.11_google-api/google-api/Pipfile)
- [Pipfile.lock](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6714_python_3.11_google-api/google-api/Pipfile.lock)
2. Review the README to make sure there are no references to Python 3.7
- [README.md](https://github.com/bcgov/GDX-Analytics-microservice/b …
=> Updated google-api to use python 3.8

s3_to_sfts/Pipfile, s3_to_sfts/Pipfile.lock
Updates the s3_to_sfts microservice's virtual environment to use Python 3.8. As there was no reference to the Python version in this microservice's README, no changes were made.
Testing the changes in this microservice requires a file to be modified. This test file will be attached to the ticket 
1. Review the virtual environment files to make sure the Python version is set to 3.8
- [Pipfile](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6712_python3.8_s3_to_sfts/s3_to_sfts/Pipfile)
- [Pipfile.lock](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6712_python3.8_s3_to_sfts/s3_to_sfts/Pipfile.lock)
2. Review the README to make sure there are no references to Python 3.7
- [README.md](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-6712_python3 …
=> Updated python to 3.8

looker_dashboard_usage/Pipfile, looker_dashboard_usage/Pipfile.lock, looker_dashboard_usage/looker_dashboard_usage.py
1. Changes the connection in the looker_dashboard_usage microservice to use and SQLAlchemy engine 
2. Changes the DBAPI from using mysql-connector-python to PyMySQL
3. As a consequence, updated the dashboard.history query to escape the '%' character
Testing the changes in this microservice requires a file to be modified. This test file will be attached to the ticket 
1. Review the virtual environment files to make sure SQLAlchemy and PyMySQL is installed
- [Pipfile](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-7112_looker_dashboard_usage_sqlalchemy/looker_dashboard_usage/Pipfile)
- [Pipfile.lock](https://github.com/bcgov/GDX-Analytics-microservice/blob/GDXDSD-7112_looker_dashboard_usage_sqlalchemy/looker_dashboard_usage/Pipfile.lock)
1. Log into the ec2 instance through …
=> Gdxdsd 7112 looker dashboard usage sqlalchemy

s3_to_redshift/config.d/microservice.history.json
Defines the 'message' column as a string for the microservice.history config
Please note that a modified config is needed to test this PR. This file already exists on EC2 and a copy is attached to the ticket.
1. Log into the ec2 instance through the following commands
```
$ awsmfa prod ######
Generating new IAM STS Token ...
STS Session Token generated and saved in profile mfa successfully.
$ microservice_ssm
$ cd /home/microservice/branch/GDXDSD-7221_dtype_warning_microservice_history_20240814/s3_to_redshift
```
2. Run the following command to test the cmslitemetadat_to_redshift microservice and compare its output to what's expected.
```
$ /home/microservice/.local/bin/pipenv run python3.8 s3_to_redshift.py config.d/microservice.history.json 
```
```
Report: s3_to_redshift.py
Config: …
```
=> Defined 'message' column as string

looker_dashboard_usage/looker_dashboard_usage.json, looker_dashboard_usage/looker_dashboard_usage.py
Updated cron email output to:
List of objects successfully fully ingested from MySQL, processed, and loaded to S3 ('good'):
=> Gdxdsd-7111-cron-email format update

derived_assets_to_redshift/build_derived_assets.py, lib/redshift.py
This PR adds a print statement to clean_exit() function in build_derived_assets.py and edits the error message in redshift.py
Please refer to the ticket for testing instructions.
=> added print statement to build_derived_assets.py

google_search/config.d/config_search.json
Removes the energystepcode.ca entry from [config_search.json](https://github.com/bcgov/GDX-Analytics-microservice/commit/dd82a21472ae27c3b0e701c3edb989628c0a99f2#diff-1e447eb8f2aad2bcb8d54e818bd23366674f3173e7ec3944376e6236f9809378)
This action is needed as the microservice was experiencing issues with that site. Once the issues have been resolved, the site will be added back into the config. 
Please note that some files were modified for testing purposes. You can see these modified files attached in the ticket.
1. Run the following command to login to EC2
```
$ awsmfa prod ######
Generating new IAM STS Token ...
STS Session Token generated and saved in profile mfa successfully.
$ microservice_ssm
```
2. Run the following command to change to the development branch:
```
cd …
```
=> Removing energystepcode.ca while fix is worked on
